spring:
  application:
    name: @artifactId@

server:
  port: 7788
  servlet:
    context-path: /sso

security:
  oauth2:
    client:
      client-id: web
      client-secret: web
      access-token-uri: http://localhost:8888/oauth/token
      user-authorization-uri: http://localhost:8888/oauth/authorize
      scope: server
    resource:
      loadBalanced: true
      token-info-uri: http://localhost:8888/oauth/check_token
